/**
 * Enum bonding in-game item names to their names.
 */
export enum GameItemNamesEnum {
    BLACK_DRAGON_LEATHER = 'Black dragon leather',
    BLACK_DRAGONHIDE_BODY = 'Black d\'hide body',
    BLACK_DRAGONHIDE_CHAPS = 'Black d\'hide chaps',
    BLACK_DRAGONHIDE_VAMBRACES = 'Black d\'hide vambraces',
    BLUE_DRAGON_LEATHER = 'Blue dragon leather',
    BLUE_DRAGONHIDE_BODY = 'Blue d\'hide body',
    BLUE_DRAGONHIDE_CHAPS = 'Blue d\'hide chaps',
    BLUE_DRAGONHIDE_VAMBRACES = 'Blue d\'hide vambraces',
    GREEN_DRAGON_LEATHER = 'Green dragon leather',
    GREEN_DRAGONHIDE_BODY = 'Green d\'hide body',
    GREEN_DRAGONHIDE_CHAPS = 'Green d\'hide chaps',
    GREEN_DRAGONHIDE_VAMBRACES = 'Green d\'hide vambraces',
    HAMMER = 'Hammer',
    HARD_LEATHER = 'Hard leather',
    HARD_LEATHER_BODY = 'Hard leather body',
    IRON_NAILS = 'Iron nails',
    KNIFE = 'Knife',
    LEATHER = 'Leather',
    LEATHER_GLOVES = 'Leather gloves',
    LEATHER_BOOTS = 'Leather boots',
    LEATHER_COWL = 'Leather cowl',
    LEATHER_VAMBRACES = 'Leather vambraces',
    LEATHER_BODY = 'Leather body',
    LEATHER_CHAPS = 'Leather chaps',
    NEEDLE = 'Needle',
    RED_DRAGON_LEATHER = 'Red dragon leather',
    RED_DRAGONHIDE_BODY = 'Red d\'hide body',
    RED_DRAGONHIDE_CHAPS = 'Red d\'hide chaps',
    RED_DRAGONHIDE_VAMBRACES = 'Red d\'hide vambraces',
    SNAKESKIN = 'Snakeskin',
    SNAKESKIN_BOOTS = 'Snakeskin boots',
    SNAKESKIN_VAMBRACES = 'Snakeskin vambraces',
    SNAKESKIN_BANDANA = 'Snakeskin bandana',
    SNAKESKIN_CHAPS = 'Snakeskin d\'hide chaps',
    SNAKESKIN_BODY = 'Snakeskin body',
    SNAKESKIN_SHIELD = 'Snakeskin shield',
    THREAD = 'Thread',
    WILLOW_LOGS = 'Willow logs',
    WILLOW_SHIELD = 'Willow shield',
}
